http://localhost:3000/
###
POST http://localhost:3000/inicio
Content-Type: application/json

{
    "username" : "Lucio"
}
###
POST https://deploy-railway-2023.up.railway.app/inicio
Content-Type: application/json

{
    "username" : "Lucio"
}